# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6aab40e8ed12fd1dec7d21e2df396212bb6a2804c228a125974f7553ed4f502b46ab72e6aeb871c2c0d61a4eefc28f73f23790fc27625a4c4c6afd542d60e90e

test:
  secret_key_base: a28fc65ee167f6a0157460b973e2486d0b411225ca33d5fde329eb4c9112ef0727774aa6126607c04d0dba8e002d003d29e5c22ec066646fcb8ac93898b6d7dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
